#!/usr/bin/env python3
"""
The demo brain: what engram does that a vector store does not.

    python3 demo_theatre.py            # seed, then run the demonstration
    python3 demo_theatre.py --verify   # run it as a pass/fail install check

WHAT THIS IS FOR, and what it deliberately does not claim.

It is easy to demo a memory system badly: ask it questions, watch it return
relevant documents, conclude it works. That proves nothing — a competent vector
store does the same, and on a freshly-seeded brain engram's retrieval is good
but NOT categorically better. We measured that rather than assuming it (see
docs/WHAT_WE_MEASURED.md), and it would be dishonest to build a demo around
retrieval quality.

So this demonstrates three behaviours a top-k vector store structurally cannot
have, all visible on a cold brain with no usage history:

  1. COLLAPSE      — how many answers are there? Not "give me five".
  2. SUPERSESSION  — is this still true? A vector index has no concept of a
                     fact being replaced.
  3. TEMPORAL      — should this be read as past, current or upcoming, judged
                     against today rather than against the wording?

And with --warm, the one that normally takes months to appear:

  4. ASSOCIATION   — what is linked by USE rather than by meaning. This needs a
                     graph, and a graph needs someone to have used the brain, so
                     --warm simulates a few weeks of work first and shows you the
                     same query before and after. The work is simulated and
                     visible in tests/bench/warm_graph.py; nothing is pre-baked.

The corpus is a fictional 340-seat producing theatre — chosen to be unlike
anything engram was tuned on, so what you see is not a home-ground advantage.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

CORPUS = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "tests", "bench", "theatre_corpus.json")

# Every question below was VERIFIED against this corpus before being written in.
# A demo question that does not work is worse than no demo at all: it is the
# first thing a reader tries and the first thing they learn.

# (question, must_cut) — the ASSERTION IS THE BEHAVIOUR, not a count.
#
# The first version asserted exact counts (3, 2, 5) and failed on a fresh seed:
# collapse cuts where the relevance scores fall off a cliff, and the scores
# depend on the lens text, which was being regenerated by a model each time.
# The lenses now ship as fixed data, but pinning a demo to an exact integer was
# over-specifying regardless — what is being shown is "fewer when fewer are
# relevant", and that is what should be checked.
COLLAPSE_CASES = [
    ("what happened with the boiler", True),
    ("what problems have we had with damp", True),
    # Included ON PURPOSE. Collapse is not a trimming trick — when everything
    # really is relevant it returns everything, and a demo that only ever showed
    # cuts would misrepresent what it does.
    ("what maintenance is outstanding", False),
]

# (question, subject_fragment_of_the_CURRENT_answer)
SUPERSEDE_CASES = [
    ("when does the bar stop serving", "midnight"),
    ("how much did the Arts Council actually give us", "£142,000"),
    ("what is a standard evening ticket", "£21"),
]

# (question, expected_temporal_status)
TEMPORAL_CASES = [
    ("the Seagull press night", "past"),
    ("Brassed Off run in the main house", "current"),
    ("National Portfolio submission deadline", "upcoming"),
]


def seeded(conn, project):
    cur = conn.cursor()
    cur.execute("SELECT count(*) FROM memories WHERE project = %s", (project,))
    n = cur.fetchone()[0]
    cur.close()
    return n


def seed():
    """Seed from fixed data, not from a generator — see export_corpus.py."""
    from path_memory.db import get_conn
    from path_memory.memory import Memory

    with open(CORPUS) as fh:
        payload = json.load(fh)
    project = payload["project"]

    conn = get_conn()
    have = seeded(conn, project)
    if have >= len(payload["memories"]):
        conn.close()
        print(f"Demo brain already seeded ({have} memories).")
        return project
    conn.close()

    print(f"Seeding {len(payload['memories'])} memories "
          f"(this embeds each one, so it takes a minute)...")
    from path_memory.embed import embed_one

    ids = []
    conn = get_conn()
    cur = conn.cursor()
    for i, m in enumerate(payload["memories"]):
        # perspectives=False: the lenses come from the file rather than from a
        # model. Regenerating them made the demo non-reproducible (they are
        # written at temperature, so each seed produced a different index and
        # moved the collapse cliff), and it charged whoever seeded it one model
        # call per memory for text we already have.
        mid = Memory.save(
            subject=m["subject"], body=m["body"], project=project, tier="curated",
            perspectives=False,
            temporal_anchor_start=m.get("anchor_start"),
            temporal_anchor_end=m.get("anchor_end"))
        ids.append(mid)
        for lens in m.get("lenses", []):
            vec = embed_one(lens["content"])
            cur.execute(
                "INSERT INTO memory_perspectives (memory_id, perspective, content, embedding) "
                "VALUES (%s, %s, %s, %s::vector)",
                (mid, lens["perspective"], lens["content"],
                 "[" + ",".join(str(x) for x in vec) + "]"))
        if (i + 1) % 50 == 0:
            conn.commit()
            print(f"  {i + 1}/{len(payload['memories'])}", flush=True)
    conn.commit()
    cur.close()
    conn.close()
    for old_i, new_i in payload["supersedes"]:
        Memory.supersede(ids[old_i], ids[new_i])
    print(f"Seeded {len(ids)} memories, {len(payload['supersedes'])} superseded.\n")
    return project


def run(verify=False):
    from path_memory.recall import recall
    failures = []

    print("=" * 72)
    print("1. COLLAPSE — 'how many answers are there?', not 'give me five'")
    print("=" * 72)
    print("A vector store returns k results whatever you ask. If two are real and")
    print("three are noise, nothing tells you where the boundary is.\n")
    for q, expected in COLLAPSE_CASES:
        plain = recall(q, limit=5, increment_weight=False)
        cut = recall(q, limit=5, collapse=True, increment_weight=False)
        verdict = "returns everything — all five are genuinely relevant" \
            if len(cut) == len(plain) else f"cut to {len(cut)}"
        print(f"  {q!r}")
        print(f"     top-5: {len(plain)} results   collapse: {len(cut)}  <- {verdict}")
        for h in cut:
            print(f"        [{h['id']}] {h['subject'][:60]}")
        did_cut = len(cut) < len(plain)
        if did_cut != expected:
            failures.append(
                f"collapse {q!r}: expected {'a cut' if expected else 'no cut'}, "
                f"got {len(cut)} of {len(plain)}")
        print()

    print("=" * 72)
    print("2. SUPERSESSION — 'is this still true?'")
    print("=" * 72)
    print("Each of these facts CHANGED. Both versions are still stored; the")
    print("replacement outranks the original, and the original stays auditable.\n")
    for q, fragment in SUPERSEDE_CASES:
        hits = recall(q, limit=3, increment_weight=False)
        print(f"  {q!r}")
        for i, h in enumerate(hits):
            tag = "   <-- superseded, kept for the record" if h.get("superseded_by") else ""
            print(f"     {i + 1}. [{h['id']}] {h['subject'][:58]}{tag}")
        top = hits[0]["subject"] if hits else ""
        if fragment.lower() not in top.lower():
            failures.append(f"supersede {q!r}: current answer not first (got {top[:40]!r})")
        print()

    print("=" * 72)
    print("3. TEMPORAL — judged against today, not against the wording")
    print("=" * 72)
    print("The prose never changes. The tense is re-derived on every recall, so a")
    print("deadline stops reading as 'upcoming' the moment it is not.\n")
    for q, expected in TEMPORAL_CASES:
        hits = recall(q, limit=1, increment_weight=False)
        if not hits:
            failures.append(f"temporal {q!r}: nothing returned")
            continue
        h = hits[0]
        got = (h.get("temporal_status") or "none").lower()
        print(f"  [{h['id']}] {h['subject'][:50]:<52} -> {got.upper()}")
        if got != expected:
            failures.append(f"temporal {q!r}: expected {expected}, got {got}")

    print("\n" + "=" * 72)
    print("What this does NOT show, stated plainly")
    print("=" * 72)
    print("Retrieval quality. On a cold brain engram finds things about as well as")
    print("a good vector store — measured, not assumed. The behaviour that needs")
    print("usage history to appear (memories linked by what gets used together)")
    print("cannot be demonstrated on a brain seeded a minute ago. It shows up")
    print("after weeks of real use, which is the one thing a demo cannot fake.")

    if verify:
        print()
        if failures:
            print(f"FAILED — {len(failures)} check(s):")
            for f in failures:
                print(f"  - {f}")
            return 1
        n = len(COLLAPSE_CASES) + len(SUPERSEDE_CASES) + len(TEMPORAL_CASES)
        print(f"{n}/{n} checks passed.")
    return 0


def show_association():
    """Section 4: what a warm graph surfaces that similarity cannot.

    Runs the query BEFORE warming, simulates work, then runs it again — so the
    difference is visible rather than asserted. The alternative was shipping a
    pre-warmed graph, which would show the same output while hiding the fact
    that the warmth was manufactured. Showing the mechanism is the honest form.
    """
    from path_memory.db import get_conn
    from path_memory.recall import recall
    from path_memory.links import spreading_activate
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    "tests", "bench"))
    from warm_graph import warm, SESSIONS

    probe = "what should I worry about before the funding deadline"
    print("=" * 72)
    print("4. ASSOCIATION — linked by USE, not by meaning")
    print("=" * 72)
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("SELECT count(*) FROM path_edge_summary")
    before_edges = cur.fetchone()[0]
    cur.close()

    hits = recall(probe, limit=5, increment_weight=False)
    seed_ids = [h["id"] for h in hits]
    cold = spreading_activate(conn, seed_ids=seed_ids[:1], limit=6)
    print(f"\n  Query: {probe!r}")
    print(f"  Graph edges right now: {before_edges}")
    print(f"  Linked by use: {len(cold)}  <- nothing, because nobody has used this brain yet\n")

    print(f"  Simulating work: {len(SESSIONS)} jobs someone here would actually do")
    print("  (preparing the funding submission, chasing the insurance claim,")
    print("   casting the winter show, sorting the bar, planning the tour...)\n")
    r = warm(rounds=3, verbose=False)
    print(f"  {r['queries']} queries later: {r['edges']} edges, "
          f"{r['warm_memories']} memories now carry weight\n")

    hits = recall(probe, limit=5, increment_weight=False)
    ids = [h["id"] for h in hits]
    act = [a for a in spreading_activate(conn, seed_ids=ids[:1], limit=8)
           if a["id"] not in ids]
    print("  Same query. Similarity still returns:")
    for h in hits[:3]:
        print(f"     [{h['id']}] {h['subject'][:58]}")
    print("\n  And the use-built graph now ALSO surfaces:")
    for a in act[:4]:
        print(f"     [{a['id']}] activation {a['activation']:.3f}  {a['subject'][:52]}")
    print("\n  Those are not near-matches for the question. They are what someone")
    print("  doing this job kept needing at the same time. No amount of embedding")
    print("  similarity finds them, because they are not similar — they are USED")
    print("  together. On a real brain this accrues from your work, not a script.")
    conn.close()
    return len(act) > 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true",
                    help="exit non-zero if any demonstration does not behave as documented")
    ap.add_argument("--warm", action="store_true",
                    help="also simulate use and demonstrate the use-built association graph "
                         "(takes about a minute, and permanently warms this demo brain)")
    args = ap.parse_args()
    seed()
    rc = run(verify=args.verify)
    if args.warm:
        print()
        if not show_association():
            print("  (no associations formed — warming did not take)")
            rc = rc or 1
    raise SystemExit(rc)


if __name__ == "__main__":
    main()
