#!/usr/bin/env python3
"""
Export the theatre brain to a JSON file the demo can seed from.

WHY DATA AND NOT A GENERATOR. The corpus was written by ~30 Sonnet calls. A
buyer opening the AMI cannot run those — it would cost them money, need an
Anthropic key before they have any reason to trust us, and produce a DIFFERENT
corpus every time, so no shipped question could be verified against it. The demo
has to seed from fixed data.

Embeddings are deliberately NOT exported. They are 3KB per memory (~640KB here),
they are specific to one embedding model, and re-embedding on seed is fast and
uses whichever provider the buyer's instance is configured for. Shipping vectors
would silently break any instance not on gemini-embedding-001.

Supersession is exported as INDEX pairs rather than ids, because ids are assigned
at seed time on the target brain and will not match these.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from path_memory.db import get_conn

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "theatre_corpus.json")


def main():
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("""SELECT id, subject, body, temporal_anchor_start,
                          temporal_anchor_end, superseded_by
                     FROM memories WHERE archived = false ORDER BY id""")
    rows = cur.fetchall()

    # THE LENSES SHIP WITH THE CORPUS, and that is a correctness fix rather
    # than an optimisation. They are generated by a model at temperature, so
    # re-generating them on each seed produced a DIFFERENT index every time —
    # which moved the collapse cliff and made the demo's own assertions fail on
    # a fresh brain. Fixed text means a reproducible demonstration, and saves
    # whoever seeds it one model call per memory.
    cur.execute("""SELECT memory_id, perspective, content
                     FROM memory_perspectives ORDER BY memory_id, perspective""")
    lenses = {}
    for mid, kind, content in cur.fetchall():
        lenses.setdefault(mid, []).append({"perspective": kind, "content": content})
    cur.close()
    conn.close()

    index_of = {r[0]: i for i, r in enumerate(rows)}
    memories, supersedes = [], []
    for i, (mid, subject, body, a_start, a_end, sup) in enumerate(rows):
        entry = {"subject": subject, "body": body}
        if lenses.get(mid):
            entry["lenses"] = lenses[mid]
        if a_start:
            entry["anchor_start"] = str(a_start)
            entry["anchor_end"] = str(a_end) if a_end else str(a_start)
        memories.append(entry)
        if sup is not None and sup in index_of:
            supersedes.append([i, index_of[sup]])

    payload = {
        "project": "harrowgate",
        "note": ("A fictional 340-seat producing theatre. Written to be UNLIKE "
                 "the corpus engram was tuned on, so the bench measures "
                 "generalisation rather than fit."),
        "memories": memories,
        "supersedes": supersedes,
    }
    with open(OUT, "w") as fh:
        json.dump(payload, fh, indent=1)
    size = os.path.getsize(OUT)
    print(f"exported {len(memories)} memories, {len(supersedes)} supersession "
          f"pairs, {sum(1 for m in memories if 'anchor_start' in m)} anchored, "
          f"{sum(len(m.get('lenses', [])) for m in memories)} lenses "
          f"-> {OUT} ({size // 1024}KB)")


if __name__ == "__main__":
    main()
